// Class:  I2.Loc.ScriptLocalization (static, code-generated by I2 Localization)
// GUID:   f53fb97951c64dd1e9fcbbe4d8adbb70 (preserved via .meta)
// Source: KTO_Resources/il2cpp_full_dump/dump.cs (TypeDefIndex 1465)
//
// DEVIATION 2026-04-25:
// - I2 Localization is a paid Unity Asset Store package not redistributable.
//   thanmaorigin's localization is handled by KTO.Localization.LanguageModule
//   (port matches gốc IL2CPP LanguageModule.Get).
// - We provide minimal static getter shims that route to LanguageModule.Get(key)
//   so KKUpdater code (which uses ScriptLocalization.UnableConnectServer etc.)
//   compiles + runs. The keys here are the same Chinese strings gốc I2 used.

namespace I2.Loc
{
    public static class ScriptLocalization
    {
        // gốc keys recovered from dump:
        //   ScriptLocalization.UnableConnectServer  → "无法连接服务器"
        //   ScriptLocalization.QuitGame             → "退出游戏"
        //   ScriptLocalization.Cancel               → "取消"
        //   ScriptLocalization.Ok                   → "确定"
        //
        // For thanmaorigin we route these through LanguageModule.Get so they get
        // Vietnamese translations from translations_vi-VN.json.
        // (DEVIATION: gốc returns I2-cached value; we use simple dictionary lookup.)
        public static string Cancel => Resolve("取消", "Hủy");
        public static string Ok => Resolve("确定", "Đồng ý");
        public static string QuitGame => Resolve("退出游戏", "Thoát game");
        public static string UnableConnectServer => Resolve("无法连接服务器", "Không thể kết nối tới máy chủ");

        private static string Resolve(string zh, string viFallback)
        {
            // DEVIATION: thanmaorigin LanguageModule may not be ported yet at this layer.
            // Return Vietnamese fallback directly. zh kept as documentation of original key.
            _ = zh;
            return viFallback;
        }
    }
}
